/**
 * generate-product-name-review.ts  (Phase 1 — Parse & propose)
 *
 * One-off, READ-ONLY. Reads every active product (joined to category / material /
 * production type), parses each current name into canonical slots, computes the
 * proposed name via the SHARED `computeProductName`, and emits the human-review
 * table to docs/plans/ongoing/product-name-homogenization-review.md.
 *
 * Nothing is written to the database. Mauricio edits slot values in the emitted
 * table (Phase 2); Phase 3 generates the backfill migration from the approved table.
 *
 * Run:  npx ts-node scripts/generate-product-name-review.ts
 * (reads MYSQL_URL from .env)
 */

import mysql from 'mysql2/promise';
import * as fs from 'fs';
import * as path from 'path';
import {
    parseProductName,
    slotsToString,
    ProductRow,
} from '../src/modules/production/products/product-name/parse-product-name';
import { computeProductName } from '../src/modules/production/products/product-name/compute-product-name';

function readMysqlUrl(): string {
    const env = fs.readFileSync(path.join(__dirname, '..', '.env'), 'utf8');
    const m = env.match(/^MYSQL_URL=(.*)$/m);
    if (!m) throw new Error('MYSQL_URL not found in .env');
    return m[1].trim().replace(/^["']|["']$/g, '');
}

function md(cell: string | number | null | undefined): string {
    if (cell === null || cell === undefined) return '';
    return String(cell).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

async function main() {
    const connection = await mysql.createConnection(readMysqlUrl());
    const [rows] = await connection.query(`
        SELECT p.id, p.code, p.external_description, p.internal_description,
               p.width, p.length, p.pleat, p.calibre, p.discontinued,
               p.order_production_type_id, opt.name AS prod_type,
               p.product_category_id, pc.name AS category,
               p.product_material_id, pm.name AS material
        FROM products p
        LEFT JOIN order_production_type opt ON opt.id = p.order_production_type_id
        LEFT JOIN product_categories pc ON pc.id = p.product_category_id
        LEFT JOIN product_materials pm ON pm.id = p.product_material_id
        WHERE p.active = 1
        ORDER BY p.id
    `);
    await connection.end();

    const products = rows as ProductRow[];

    // Duplicate codes (class 8) — reported, out of scope for renaming.
    const byCode = new Map<string, number[]>();
    for (const r of products) {
        const key = (r.code || '').trim();
        if (!byCode.has(key)) byCode.set(key, []);
        byCode.get(key)!.push(r.id);
    }
    const dupCodes = [...byCode.entries()].filter(([, ids]) => ids.length > 1);

    const parsed = products.map((row) => {
        const res = parseProductName(row);
        const computedName = computeProductName(res.slots);
        return { row, ...res, computedName };
    });

    const flaggedCount = parsed.filter((p) => p.flags.length > 0).length;
    const manualCount = parsed.filter((p) => !p.slots.computed).length;

    // ---- render markdown ----
    const out: string[] = [];
    out.push('# Product Name Homogenization — Review Table');
    out.push('');
    out.push(
        '> **Auto-generated by `scripts/generate-product-name-review.ts` (Phase 1). Do not hand-edit the generator output blindly** —',
    );
    out.push(
        '> this file is the human-review surface (Phase 2). Edit the **slot columns** (not the computed name), resolve every',
    );
    out.push(
        '> flagged conflict, and settle one official casing per brand/color/presentation token. Phase 3 backfills from the',
    );
    out.push(
        '> approved slots; the proposed name is always `computeProductName(slots)`. The **current aliases** column is preserved',
    );
    out.push(
        '> here as the permanent record — the migration discards the old free-form alias lists and substitutes the old display name.',
    );
    out.push('');
    out.push('## Summary');
    out.push('');
    out.push(`- Active products: **${products.length}**`);
    out.push(`- Rows with at least one flag: **${flaggedCount}**`);
    out.push(`- Rows proposed \`computed_name = false\` (placeholders/one-offs): **${manualCount}**`);
    out.push(`- Duplicate \`code\` groups (class 8, out of scope): **${dupCodes.length}**`);
    out.push('');

    if (dupCodes.length) {
        out.push('### Duplicate codes (report only — handled as its own fix if desired)');
        out.push('');
        out.push('| code | product ids |');
        out.push('| --- | --- |');
        for (const [code, ids] of dupCodes) {
            out.push(`| ${md(code)} | ${ids.join(', ')} |`);
        }
        out.push('');
    }

    // Discovered catalog tokens (what the parser actually assigned).
    const tokenSet = (pick: (s: ReturnType<typeof parseProductName>['slots']) => string | null | undefined) => {
        const set = new Set<string>();
        for (const p of parsed) {
            const v = pick(p.slots);
            if (v) set.add(v);
        }
        return [...set].sort();
    };
    out.push('### Discovered catalog tokens (become the catalog rows in Phase 3)');
    out.push('');
    out.push(`- **Tipo:** ${tokenSet((s) => s.tipo).join(' · ') || '—'}`);
    out.push(`- **Color:** ${tokenSet((s) => s.color).join(' · ') || '—'}`);
    out.push(`- **Línea/Uso:** ${tokenSet((s) => s.linea).join(' · ') || '—'}`);
    out.push(`- **Marca:** ${tokenSet((s) => s.brand).join(' · ') || '—'}`);
    out.push(`- **Presentación:** ${tokenSet((s) => s.presentation).join(' · ') || '—'}`);
    out.push('');

    out.push('## Review table');
    out.push('');
    out.push(
        '| id | code | disc | current name | current aliases (record) | slots (edit these) | proposed name | flags |',
    );
    out.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const p of parsed) {
        const disc = p.row.discontinued === 1 || p.row.discontinued === true ? 'Y' : '';
        out.push(
            `| ${p.row.id} | ${md(p.row.code)} | ${disc} | ${md(p.row.external_description)} | ${md(
                p.row.internal_description,
            )} | ${md(slotsToString(p.slots))} | ${md(p.computedName)} | ${md(
                p.flags.join('; '),
            )} |`,
        );
    }
    out.push('');

    // Flag detail appendix (grouped) for scanning.
    out.push('## Flagged rows (detail)');
    out.push('');
    for (const p of parsed.filter((x) => x.flags.length)) {
        out.push(`- **${p.row.id}** \`${md(p.row.code)}\` — "${md(p.row.external_description)}"`);
        for (const f of p.flags) out.push(`  - ${md(f)}`);
        out.push(`  - → proposed: **${md(p.computedName)}**`);
    }
    out.push('');

    const target = path.join(
        __dirname,
        '..',
        '..',
        'docs',
        'plans',
        'ongoing',
        'product-name-homogenization-review.md',
    );
    fs.writeFileSync(target, out.join('\n'), 'utf8');
    // eslint-disable-next-line no-console
    console.log(
        `Wrote ${target}\n  products=${products.length} flagged=${flaggedCount} manual=${manualCount} dupCodes=${dupCodes.length}`,
    );
}

main().catch((e) => {
    // eslint-disable-next-line no-console
    console.error(e);
    process.exit(1);
});
